Modal Pop Window
Kwentsir/Kwentsir-Portfolio pull request #16
Opened 2022-04-15 11:42 UTC by Kwentsir

In this project, the following were implemented:

- When the user clicks (or taps) the button to check project details, the popup with details about the project appears.

- When the user clicks (or taps) the close (X) button, the popup disappears.

2022-04-15 11:50 UTC, ShoiraTa commented
Hi  👋🏻 ,
While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 😢 

### Invalid Code Review Request

-This is a pair programming activity, but there is only 1 contributor. Please make sure that both participants make contributions. 

 **Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray** 

Cheers and Happy coding! 👏🏻👏🏻 

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear._

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

***

_Invalid Code Review Request Does not count into the code reviews limit._

2022-04-15 15:04 UTC, MeqdamAlqudah requested changes
Hi @Kwentsir , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
![](https://media3.giphy.com/media/neUaH5fz6ZpefE2KBP/200.webp?cid=ecf05e47vi29c90ou1pmr80rysyvlnhlrrvlc553tkj8xbvv&rid=200.webp&ct=g)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-15 15:04 UTC, MeqdamAlqudah commented on script.js
> +const navMenu = document.querySelector('.mobile-list');
- [ ] Please make sure that you have 4 checks for linters for HTML And CSS and JavaScript 
![image](https://user-images.githubusercontent.com/74744787/163574014-5c053850-db7a-4d53-88a6-30948646bf5d.png)

2022-04-15 15:04 UTC, MeqdamAlqudah commented on script.js
>      <div class="desktop-popimages">
- [ ] Please add a margin to the top and to the bottom of the popup window so it matches Figma design 

| Your design | Figma |
| ------------- | ------- |
| ![image](https://user-images.githubusercontent.com/74744787/163586031-a48cc033-8238-4641-8b93-d55c7321462e.png)
![image](https://user-images.githubusercontent.com/74744787/163586059-312b91ae-92fa-4176-a588-492246a40750.png) | ![image](https://user-images.githubusercontent.com/74744787/163586115-41993285-7624-430c-9bc4-db744447cb12.png) |

2022-04-16 04:52 UTC, aimemalaika approved these changes
Hi @Kwentsir , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-16 05:27 UTC, merged